---
- hosts: chrome
  gather_facts: True
  ignore_unreachable: yes
  become: True
  become_user: amogh.pawaskar
  tasks:
    - name: Check Chrome Version
      shell: google-chrome --version
      register: version_status

    - debug: 
        var: version_status.stdout
